//ERRORS

const BAD_REQUEST_ERROR_STATUS_CODE = 400;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const RESOURCE_NOT_FOUND_ERROR_STATUS_CODE = 404;
//SUCCESS

const OK_STATUS_CODE = 200;
const RESOURCE_CREATED_STATUS_CODE = 201;

const RESOURCE_NOT_FOUND_MESSAGE =
  "Resource not found. The requested resource could not be found on this server.";

module.exports = {
  BAD_REQUEST_ERROR_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  RESOURCE_NOT_FOUND_ERROR_STATUS_CODE,
  RESOURCE_CREATED_STATUS_CODE,
  OK_STATUS_CODE,
  RESOURCE_NOT_FOUND_MESSAGE,
};
